#!/bin/bash

if [[ $EUID > 0 ]]
    then echo "Please run as root"
    exit
fi

current=$(sed -n '3p' /etc/prime/config)

if [[ $1 = "switch" ]]; then
     if [[ $2 = "intel" ]]; then
               if [[ $current = "I" ]]; then
                 echo "Intel VGA already in use!!!"
                 else
                 echo "Please logout to switch graphics"
                 sed -i '1 c2' /etc/prime/config
                 systemctl start prime_logout.waiting &
                 fi
   elif [[ $2 = "nvidia" ]]; then
               if [[ $current = "D" ]]; then
                 echo "Nvidia VGA already in use!!!"
                 else
                 echo "Please logout to switch graphics"
                 sed -i '1 c1' /etc/prime/config
                 systemctl start prime_logout.waiting &
                 fi      
      else
                echo "Use: vga switch intel|nvidia"     
         fi

elif [[ $1 = "default" ]]; then
     if [[ $2 = "intel" ]]; then
        echo "Boot default: Intel"
        sed -i '2 cI' /etc/prime/config
   elif [[ $2 = "nvidia" ]]; then
        echo "Boot default: Nvidia"
        sed -i '2 cD' /etc/prime/config  
   elif [[ $2 = "keep" ]]; then
        sed -i '2 cL' /etc/prime/config   
        echo "Boot default: Latest Session"
    else
        echo "Use: vga default intel|nvidia|keep" 
        fi

else
 
echo -e "USE: \n\nvga switch intel|nvidia : \nHot Switch (logout required)\n\n\nvga default intel|nvidia|keep: \nset default VGA on boot (keep > remember latest session)"

fi
